from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("queue", views.today, name="today"),
    path("all", views.all_postings, name="all"),
    path("all/<str:user_ref>", views.all_postings, name="all_user"),
    path("app/<int:app_id>", views.app_detail, name="app_detail"),
    path("stats", views.stats, name="stats"),
    path("sources", views.sources, name="sources"),
    path("applicants", views.applicants_index, name="applicants"),
    path("onboard", views.onboard, name="onboard"),
    path("go", views.go_to_matches, name="go"),
    path("confirm/<str:user_ref>/<str:token>", views.confirm_signup,
         name="confirm_signup"),
    path("outcome/<int:outcome_id>/link", views.outcome_link, name="outcome_link"),
    path("job_matches/<str:user_ref>", views.user_matches, name="user_matches"),
    path("job_matches/<str:user_ref>/profile_link", views.profile_link_email,
         name="profile_link_email"),
    path("job_matches/<str:user_ref>/<int:job_id>", views.job_match_detail,
         name="job_match_detail"),
    path("app/<int:app_id>/save", views.app_save, name="app_save"),
    path("app/<int:app_id>/approve", views.app_approve, name="app_approve"),
    path("app/<int:app_id>/reject", views.app_reject, name="app_reject"),
    path("app/<int:app_id>/resume", views.app_resume, name="app_resume"),
    path("app/<int:app_id>/applied", views.app_applied, name="app_applied"),
    path("profile/", views.profile_index, name="profile_index"),
    path("profile/<str:user_ref>", views.profile_shortcut,
         name="profile_shortcut"),
    path("profile/<str:user_ref>/<str:token>/resume", views.resume_upload,
         name="resume_upload"),
    path("profile/<str:user_ref>/<str:token>", views.profile_edit,
         name="profile_edit"),
    path("api/title_suggest", views.title_suggest, name="title_suggest"),
    path("health", views.health, name="health"),
    path("healthz", views.healthz, name="healthz"),
]
